name: flutter_storage_learning
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_storage: ^11.7.7
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  file_picker: ^8.0.3
  lottie: ^3.1.2
  syncfusion_flutter_pdfviewer: ^25.2.7
  firebase_crashlytics: ^3.5.7
  firebase_analytics: ^10.10.7
  video_player: ^2.8.6
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/images/
