// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWGUKoC5YXTgsQNlcoZjSDKD-0qXovnlg',
    appId: '1:862423877258:web:997df2375a104f53280f73',
    messagingSenderId: '862423877258',
    projectId: 'flutter-storage-learning',
    authDomain: 'flutter-storage-learning.firebaseapp.com',
    storageBucket: 'flutter-storage-learning.appspot.com',
    measurementId: 'G-KSR5YJZ6XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN13sLHF_BlmVISmxC1WwwFpFJuJH3akU',
    appId: '1:862423877258:android:f3feebc4c69477a7280f73',
    messagingSenderId: '862423877258',
    projectId: 'flutter-storage-learning',
    storageBucket: 'flutter-storage-learning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfpvM_gsJCJmChYqEQel0atJ91rMtRcjw',
    appId: '1:862423877258:ios:f781af0c3dab30eb280f73',
    messagingSenderId: '862423877258',
    projectId: 'flutter-storage-learning',
    storageBucket: 'flutter-storage-learning.appspot.com',
    iosBundleId: 'com.example.flutterStorageLearning',
  );
}
